development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:7329370b65029f37f61bd8bbde73b24d@albacore.redistogo.com:9683/
  channel_prefix: twentyfourgame_production
