development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:d0b02a3597d9b04fe2e375400c05044f@albacore.redistogo.com:9776/
  channel_prefix: twentyfourgame_production
